version: 2.1

orbs:
  docker: circleci/docker@1.5.0

jobs:
  Build:
    docker:
      - image: cimg/rust:1.46.0
    resource_class: xlarge
    steps:
      - checkout
      - run: |
          rustup toolchain install nightly
          rustup default nightly
          cargo build --release --all-features
  
workflows:
  version: 2
  CircleCI:
    jobs:
      - Build